// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "../inst/include/divergenceModelR.h"
#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// affineContract_sqrtFilter
List affineContract_sqrtFilter(const arma::mat dataMat, const arma::vec initState, const arma::mat initProcCov, const List modelParams);
RcppExport SEXP divergenceModelR_affineContract_sqrtFilter(SEXP dataMatSEXP, SEXP initStateSEXP, SEXP initProcCovSEXP, SEXP modelParamsSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const arma::mat >::type dataMat(dataMatSEXP);
    Rcpp::traits::input_parameter< const arma::vec >::type initState(initStateSEXP);
    Rcpp::traits::input_parameter< const arma::mat >::type initProcCov(initProcCovSEXP);
    Rcpp::traits::input_parameter< const List >::type modelParams(modelParamsSEXP);
    __result = Rcpp::wrap(affineContract_sqrtFilter(dataMat, initState, initProcCov, modelParams));
    return __result;
END_RCPP
}
// affineObservationStateHandler
Rcpp::List affineObservationStateHandler(const arma::mat& stateMat, const Rcpp::List& modelParameters, const int iterCount);
RcppExport SEXP divergenceModelR_affineObservationStateHandler(SEXP stateMatSEXP, SEXP modelParametersSEXP, SEXP iterCountSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const arma::mat& >::type stateMat(stateMatSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type modelParameters(modelParametersSEXP);
    Rcpp::traits::input_parameter< const int >::type iterCount(iterCountSEXP);
    __result = Rcpp::wrap(affineObservationStateHandler(stateMat, modelParameters, iterCount));
    return __result;
END_RCPP
}
// affineObservationStateHandler_D
Rcpp::List affineObservationStateHandler_D(const arma::mat& stateMat, const Rcpp::List& modelParameters, const int iterCount);
RcppExport SEXP divergenceModelR_affineObservationStateHandler_D(SEXP stateMatSEXP, SEXP modelParametersSEXP, SEXP iterCountSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const arma::mat& >::type stateMat(stateMatSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type modelParameters(modelParametersSEXP);
    Rcpp::traits::input_parameter< const int >::type iterCount(iterCountSEXP);
    __result = Rcpp::wrap(affineObservationStateHandler_D(stateMat, modelParameters, iterCount));
    return __result;
END_RCPP
}
// affineObservationStateHandler_DS
Rcpp::List affineObservationStateHandler_DS(const arma::mat& stateMat, const Rcpp::List& modelParameters, const int iterCount);
RcppExport SEXP divergenceModelR_affineObservationStateHandler_DS(SEXP stateMatSEXP, SEXP modelParametersSEXP, SEXP iterCountSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const arma::mat& >::type stateMat(stateMatSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type modelParameters(modelParametersSEXP);
    Rcpp::traits::input_parameter< const int >::type iterCount(iterCountSEXP);
    __result = Rcpp::wrap(affineObservationStateHandler_DS(stateMat, modelParameters, iterCount));
    return __result;
END_RCPP
}
// affineObservationStateHandler_affineContracts
Rcpp::List affineObservationStateHandler_affineContracts(const arma::mat& stateMat, const Rcpp::List& modelParameters, const int iterCount);
RcppExport SEXP divergenceModelR_affineObservationStateHandler_affineContracts(SEXP stateMatSEXP, SEXP modelParametersSEXP, SEXP iterCountSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const arma::mat& >::type stateMat(stateMatSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type modelParameters(modelParametersSEXP);
    Rcpp::traits::input_parameter< const int >::type iterCount(iterCountSEXP);
    __result = Rcpp::wrap(affineObservationStateHandler_affineContracts(stateMat, modelParameters, iterCount));
    return __result;
END_RCPP
}
// affineObservationStateHandler_optionPortfolios
Rcpp::List affineObservationStateHandler_optionPortfolios(const arma::mat& stateMat, const Rcpp::List& modelParameters, const int iterCount);
RcppExport SEXP divergenceModelR_affineObservationStateHandler_optionPortfolios(SEXP stateMatSEXP, SEXP modelParametersSEXP, SEXP iterCountSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const arma::mat& >::type stateMat(stateMatSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type modelParameters(modelParametersSEXP);
    Rcpp::traits::input_parameter< const int >::type iterCount(iterCountSEXP);
    __result = Rcpp::wrap(affineObservationStateHandler_optionPortfolios(stateMat, modelParameters, iterCount));
    return __result;
END_RCPP
}
// affineObservationStateHandler_optionPortfolios_noStock
Rcpp::List affineObservationStateHandler_optionPortfolios_noStock(const arma::mat& stateMat, const Rcpp::List& modelParameters, const int iterCount);
RcppExport SEXP divergenceModelR_affineObservationStateHandler_optionPortfolios_noStock(SEXP stateMatSEXP, SEXP modelParametersSEXP, SEXP iterCountSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const arma::mat& >::type stateMat(stateMatSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type modelParameters(modelParametersSEXP);
    Rcpp::traits::input_parameter< const int >::type iterCount(iterCountSEXP);
    __result = Rcpp::wrap(affineObservationStateHandler_optionPortfolios_noStock(stateMat, modelParameters, iterCount));
    return __result;
END_RCPP
}
// affineTransitionStateHandler
Rcpp::List affineTransitionStateHandler(const arma::mat& stateMat, const Rcpp::List& modelParameters, const int iterCount);
RcppExport SEXP divergenceModelR_affineTransitionStateHandler(SEXP stateMatSEXP, SEXP modelParametersSEXP, SEXP iterCountSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const arma::mat& >::type stateMat(stateMatSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type modelParameters(modelParametersSEXP);
    Rcpp::traits::input_parameter< const int >::type iterCount(iterCountSEXP);
    __result = Rcpp::wrap(affineTransitionStateHandler(stateMat, modelParameters, iterCount));
    return __result;
END_RCPP
}
// covMatFun
arma::mat covMatFun(List covListS, const arma::uvec covListDim, const arma::vec currVol);
RcppExport SEXP divergenceModelR_covMatFun(SEXP covListSSEXP, SEXP covListDimSEXP, SEXP currVolSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< List >::type covListS(covListSSEXP);
    Rcpp::traits::input_parameter< const arma::uvec >::type covListDim(covListDimSEXP);
    Rcpp::traits::input_parameter< const arma::vec >::type currVol(currVolSEXP);
    __result = Rcpp::wrap(covMatFun(covListS, covListDim, currVol));
    return __result;
END_RCPP
}
// divergenceSwapRateCpp
arma::cube divergenceSwapRateCpp(const arma::vec p, const arma::cube coeffs, const arma::mat stateMat);
RcppExport SEXP divergenceModelR_divergenceSwapRateCpp(SEXP pSEXP, SEXP coeffsSEXP, SEXP stateMatSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const arma::vec >::type p(pSEXP);
    Rcpp::traits::input_parameter< const arma::cube >::type coeffs(coeffsSEXP);
    Rcpp::traits::input_parameter< const arma::mat >::type stateMat(stateMatSEXP);
    __result = Rcpp::wrap(divergenceSwapRateCpp(p, coeffs, stateMat));
    return __result;
END_RCPP
}
// skewnessSwapRateCpp
arma::cube skewnessSwapRateCpp(const arma::vec p, const arma::cube coeffs, const arma::mat stateMat);
RcppExport SEXP divergenceModelR_skewnessSwapRateCpp(SEXP pSEXP, SEXP coeffsSEXP, SEXP stateMatSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const arma::vec >::type p(pSEXP);
    Rcpp::traits::input_parameter< const arma::cube >::type coeffs(coeffsSEXP);
    Rcpp::traits::input_parameter< const arma::mat >::type stateMat(stateMatSEXP);
    __result = Rcpp::wrap(skewnessSwapRateCpp(p, coeffs, stateMat));
    return __result;
END_RCPP
}
// quarticitySwapRateCpp
arma::cube quarticitySwapRateCpp(const arma::vec p, const arma::cube coeffs, const arma::mat stateMat);
RcppExport SEXP divergenceModelR_quarticitySwapRateCpp(SEXP pSEXP, SEXP coeffsSEXP, SEXP stateMatSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const arma::vec >::type p(pSEXP);
    Rcpp::traits::input_parameter< const arma::cube >::type coeffs(coeffsSEXP);
    Rcpp::traits::input_parameter< const arma::mat >::type stateMat(stateMatSEXP);
    __result = Rcpp::wrap(quarticitySwapRateCpp(p, coeffs, stateMat));
    return __result;
END_RCPP
}
// divModelObsNoiseMat
arma::mat divModelObsNoiseMat(const arma::vec corrs, arma::vec bpars, double spotVar, const arma::vec matVec, const int U);
RcppExport SEXP divergenceModelR_divModelObsNoiseMat(SEXP corrsSEXP, SEXP bparsSEXP, SEXP spotVarSEXP, SEXP matVecSEXP, SEXP USEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const arma::vec >::type corrs(corrsSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type bpars(bparsSEXP);
    Rcpp::traits::input_parameter< double >::type spotVar(spotVarSEXP);
    Rcpp::traits::input_parameter< const arma::vec >::type matVec(matVecSEXP);
    Rcpp::traits::input_parameter< const int >::type U(USEXP);
    __result = Rcpp::wrap(divModelObsNoiseMat(corrs, bpars, spotVar, matVec, U));
    return __result;
END_RCPP
}
// portfolio_sqrtFilter
List portfolio_sqrtFilter(const arma::mat dataMat, const arma::vec initState, const arma::mat initProcCov, const List modelParams);
RcppExport SEXP divergenceModelR_portfolio_sqrtFilter(SEXP dataMatSEXP, SEXP initStateSEXP, SEXP initProcCovSEXP, SEXP modelParamsSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const arma::mat >::type dataMat(dataMatSEXP);
    Rcpp::traits::input_parameter< const arma::vec >::type initState(initStateSEXP);
    Rcpp::traits::input_parameter< const arma::mat >::type initProcCov(initProcCovSEXP);
    Rcpp::traits::input_parameter< const List >::type modelParams(modelParamsSEXP);
    __result = Rcpp::wrap(portfolio_sqrtFilter(dataMat, initState, initProcCov, modelParams));
    return __result;
END_RCPP
}
// portfolio_noStock_sqrtFilter
List portfolio_noStock_sqrtFilter(const arma::mat dataMat, const arma::vec initState, const arma::mat initProcCov, const List modelParams);
RcppExport SEXP divergenceModelR_portfolio_noStock_sqrtFilter(SEXP dataMatSEXP, SEXP initStateSEXP, SEXP initProcCovSEXP, SEXP modelParamsSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const arma::mat >::type dataMat(dataMatSEXP);
    Rcpp::traits::input_parameter< const arma::vec >::type initState(initStateSEXP);
    Rcpp::traits::input_parameter< const arma::mat >::type initProcCov(initProcCovSEXP);
    Rcpp::traits::input_parameter< const List >::type modelParams(modelParamsSEXP);
    __result = Rcpp::wrap(portfolio_noStock_sqrtFilter(dataMat, initState, initProcCov, modelParams));
    return __result;
END_RCPP
}
// DSQ_sqrtFilter
List DSQ_sqrtFilter(const arma::mat dataMat, const arma::vec initState, const arma::mat initProcCov, const List modelParams);
RcppExport SEXP divergenceModelR_DSQ_sqrtFilter(SEXP dataMatSEXP, SEXP initStateSEXP, SEXP initProcCovSEXP, SEXP modelParamsSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const arma::mat >::type dataMat(dataMatSEXP);
    Rcpp::traits::input_parameter< const arma::vec >::type initState(initStateSEXP);
    Rcpp::traits::input_parameter< const arma::mat >::type initProcCov(initProcCovSEXP);
    Rcpp::traits::input_parameter< const List >::type modelParams(modelParamsSEXP);
    __result = Rcpp::wrap(DSQ_sqrtFilter(dataMat, initState, initProcCov, modelParams));
    return __result;
END_RCPP
}
// D_sqrtFilter
List D_sqrtFilter(const arma::mat dataMat, const arma::vec initState, const arma::mat initProcCov, const List modelParams);
RcppExport SEXP divergenceModelR_D_sqrtFilter(SEXP dataMatSEXP, SEXP initStateSEXP, SEXP initProcCovSEXP, SEXP modelParamsSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const arma::mat >::type dataMat(dataMatSEXP);
    Rcpp::traits::input_parameter< const arma::vec >::type initState(initStateSEXP);
    Rcpp::traits::input_parameter< const arma::mat >::type initProcCov(initProcCovSEXP);
    Rcpp::traits::input_parameter< const List >::type modelParams(modelParamsSEXP);
    __result = Rcpp::wrap(D_sqrtFilter(dataMat, initState, initProcCov, modelParams));
    return __result;
END_RCPP
}
// DS_sqrtFilter
List DS_sqrtFilter(const arma::mat dataMat, const arma::vec initState, const arma::mat initProcCov, const List modelParams);
RcppExport SEXP divergenceModelR_DS_sqrtFilter(SEXP dataMatSEXP, SEXP initStateSEXP, SEXP initProcCovSEXP, SEXP modelParamsSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const arma::mat >::type dataMat(dataMatSEXP);
    Rcpp::traits::input_parameter< const arma::vec >::type initState(initStateSEXP);
    Rcpp::traits::input_parameter< const arma::mat >::type initProcCov(initProcCovSEXP);
    Rcpp::traits::input_parameter< const List >::type modelParams(modelParamsSEXP);
    __result = Rcpp::wrap(DS_sqrtFilter(dataMat, initState, initProcCov, modelParams));
    return __result;
END_RCPP
}
// glPricer_cpp
arma::cube glPricer_cpp(const arma::cube& strikeMat, const arma::mat& mkt, const arma::vec& glWts, const arma::vec& glNodes, arma::cx_cube& cfVals, int Nfactors, double alpha, double sigmaRef);
RcppExport SEXP divergenceModelR_glPricer_cpp(SEXP strikeMatSEXP, SEXP mktSEXP, SEXP glWtsSEXP, SEXP glNodesSEXP, SEXP cfValsSEXP, SEXP NfactorsSEXP, SEXP alphaSEXP, SEXP sigmaRefSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const arma::cube& >::type strikeMat(strikeMatSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type mkt(mktSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type glWts(glWtsSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type glNodes(glNodesSEXP);
    Rcpp::traits::input_parameter< arma::cx_cube& >::type cfVals(cfValsSEXP);
    Rcpp::traits::input_parameter< int >::type Nfactors(NfactorsSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< double >::type sigmaRef(sigmaRefSEXP);
    __result = Rcpp::wrap(glPricer_cpp(strikeMat, mkt, glWts, glNodes, cfVals, Nfactors, alpha, sigmaRef));
    return __result;
END_RCPP
}
// meanVecFun
arma::vec meanVecFun(List meanListS, const arma::vec currVol);
RcppExport SEXP divergenceModelR_meanVecFun(SEXP meanListSSEXP, SEXP currVolSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< List >::type meanListS(meanListSSEXP);
    Rcpp::traits::input_parameter< const arma::vec >::type currVol(currVolSEXP);
    __result = Rcpp::wrap(meanVecFun(meanListS, currVol));
    return __result;
END_RCPP
}
// testAffineFilter
List testAffineFilter(const arma::mat testDataMat, const arma::vec testInitState, const arma::mat testInitProcCov, const List testModelParams);
RcppExport SEXP divergenceModelR_testAffineFilter(SEXP testDataMatSEXP, SEXP testInitStateSEXP, SEXP testInitProcCovSEXP, SEXP testModelParamsSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const arma::mat >::type testDataMat(testDataMatSEXP);
    Rcpp::traits::input_parameter< const arma::vec >::type testInitState(testInitStateSEXP);
    Rcpp::traits::input_parameter< const arma::mat >::type testInitProcCov(testInitProcCovSEXP);
    Rcpp::traits::input_parameter< const List >::type testModelParams(testModelParamsSEXP);
    __result = Rcpp::wrap(testAffineFilter(testDataMat, testInitState, testInitProcCov, testModelParams));
    return __result;
END_RCPP
}
// testSqrtAffineFilter
List testSqrtAffineFilter(const arma::mat testDataMat, const arma::vec testInitState, const arma::mat testInitProcCov, const List testModelParams);
RcppExport SEXP divergenceModelR_testSqrtAffineFilter(SEXP testDataMatSEXP, SEXP testInitStateSEXP, SEXP testInitProcCovSEXP, SEXP testModelParamsSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const arma::mat >::type testDataMat(testDataMatSEXP);
    Rcpp::traits::input_parameter< const arma::vec >::type testInitState(testInitStateSEXP);
    Rcpp::traits::input_parameter< const arma::mat >::type testInitProcCov(testInitProcCovSEXP);
    Rcpp::traits::input_parameter< const List >::type testModelParams(testModelParamsSEXP);
    __result = Rcpp::wrap(testSqrtAffineFilter(testDataMat, testInitState, testInitProcCov, testModelParams));
    return __result;
END_RCPP
}
