# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @rdname filterCaller
#' @details \code{portfolio_sqrtFilter} works on whatever portfolios you supply
#' @export
affineContract_sqrtFilter <- function(dataMat, initState, initProcCov, modelParams) {
    .Call('_divergenceModelR_affineContract_sqrtFilter', PACKAGE = 'divergenceModelR', dataMat, initState, initProcCov, modelParams)
}

#' @rdname filterCaller
#' @details \code{portfolio_sqrtFilter} works on whatever portfolios you supply
#' @export
portfolio_sqrtFilter <- function(dataMat, initState, initProcCov, modelParams) {
    .Call('_divergenceModelR_portfolio_sqrtFilter', PACKAGE = 'divergenceModelR', dataMat, initState, initProcCov, modelParams)
}

#' @export
portfolio_noStock_sqrtFilter <- function(dataMat, initState, initProcCov, modelParams) {
    .Call('_divergenceModelR_portfolio_noStock_sqrtFilter', PACKAGE = 'divergenceModelR', dataMat, initState, initProcCov, modelParams)
}

#' @export
portfolio_noStock_simpleFilter <- function(dataMat, initState, initProcCov, modelParams) {
    .Call('_divergenceModelR_portfolio_noStock_simpleFilter', PACKAGE = 'divergenceModelR', dataMat, initState, initProcCov, modelParams)
}

#' @name filterCaller
#' @title C++ filter call
#' @description This function wraps the ukfClass construction and exposes the call to R. Should not be used directly by the user, rather its exported R interface should be given as an argument to \code{\link{modelLikelihood}}
#' @details \code{DSQ_sqrtFilter} works on divergence, skewness and quarticity
#' @export
DSQ_sqrtFilter <- function(dataMat, initState, initProcCov, modelParams) {
    .Call('_divergenceModelR_DSQ_sqrtFilter', PACKAGE = 'divergenceModelR', dataMat, initState, initProcCov, modelParams)
}

#' @rdname filterCaller
#' @details \code{D_sqrtFilter} works on divergence
#' @export
D_sqrtFilter <- function(dataMat, initState, initProcCov, modelParams) {
    .Call('_divergenceModelR_D_sqrtFilter', PACKAGE = 'divergenceModelR', dataMat, initState, initProcCov, modelParams)
}

#' @rdname filterCaller
#' @details \code{DS_sqrtFilter} works on divergence
#' @export
DS_sqrtFilter <- function(dataMat, initState, initProcCov, modelParams) {
    .Call('_divergenceModelR_DS_sqrtFilter', PACKAGE = 'divergenceModelR', dataMat, initState, initProcCov, modelParams)
}

#' @export
affineObservationStateHandler <- function(stateMat, modelParameters, iterCount) {
    .Call('_divergenceModelR_affineObservationStateHandler', PACKAGE = 'divergenceModelR', stateMat, modelParameters, iterCount)
}

affineObservationStateHandler_D <- function(stateMat, modelParameters, iterCount) {
    .Call('_divergenceModelR_affineObservationStateHandler_D', PACKAGE = 'divergenceModelR', stateMat, modelParameters, iterCount)
}

affineObservationStateHandler_DS <- function(stateMat, modelParameters, iterCount) {
    .Call('_divergenceModelR_affineObservationStateHandler_DS', PACKAGE = 'divergenceModelR', stateMat, modelParameters, iterCount)
}

#' @export
affineObservationStateHandler_affineContracts <- function(stateMat, modelParameters, iterCount) {
    .Call('_divergenceModelR_affineObservationStateHandler_affineContracts', PACKAGE = 'divergenceModelR', stateMat, modelParameters, iterCount)
}

#' @export
affineObservationStateHandler_cumulant <- function(stateMat, modelParameters, iterCount) {
    .Call('_divergenceModelR_affineObservationStateHandler_cumulant', PACKAGE = 'divergenceModelR', stateMat, modelParameters, iterCount)
}

affineObservationStateHandler_cumulant_D <- function(stateMat, modelParameters, iterCount) {
    .Call('_divergenceModelR_affineObservationStateHandler_cumulant_D', PACKAGE = 'divergenceModelR', stateMat, modelParameters, iterCount)
}

affineObservationStateHandler_cumulant_DS <- function(stateMat, modelParameters, iterCount) {
    .Call('_divergenceModelR_affineObservationStateHandler_cumulant_DS', PACKAGE = 'divergenceModelR', stateMat, modelParameters, iterCount)
}

#' @export
affineObservationStateHandler_optionPortfolios <- function(stateMat, modelParameters, iterCount) {
    .Call('_divergenceModelR_affineObservationStateHandler_optionPortfolios', PACKAGE = 'divergenceModelR', stateMat, modelParameters, iterCount)
}

#' @export
affineObservationStateHandler_optionPortfolios_noStock <- function(stateMat, modelParameters, iterCount) {
    .Call('_divergenceModelR_affineObservationStateHandler_optionPortfolios_noStock', PACKAGE = 'divergenceModelR', stateMat, modelParameters, iterCount)
}

#' @export
affineTransitionStateHandler <- function(stateMat, modelParameters, iterCount) {
    .Call('_divergenceModelR_affineTransitionStateHandler', PACKAGE = 'divergenceModelR', stateMat, modelParameters, iterCount)
}

#' @export
covMatFun <- function(covListS, covListDim, currVol) {
    .Call('_divergenceModelR_covMatFun', PACKAGE = 'divergenceModelR', covListS, covListDim, currVol)
}

#' @rdname filterCaller
#' @details \code{portfolio_sqrtFilter} works on whatever portfolios you supply
NULL

#' @export
cumulant_DS_sqrtFilter <- function(dataMat, initState, initProcCov, modelParams) {
    .Call('_divergenceModelR_cumulant_DS_sqrtFilter', PACKAGE = 'divergenceModelR', dataMat, initState, initProcCov, modelParams)
}

#' @export
divModelObsNoiseMat <- function(corrs, bpars, spotVar, matVec, U) {
    .Call('_divergenceModelR_divModelObsNoiseMat', PACKAGE = 'divergenceModelR', corrs, bpars, spotVar, matVec, U)
}

#' @export
divergenceSwapRateCpp <- function(p, coeffs, stateMat) {
    .Call('_divergenceModelR_divergenceSwapRateCpp', PACKAGE = 'divergenceModelR', p, coeffs, stateMat)
}

#' @export
skewnessSwapRateCpp <- function(p, coeffs, stateMat) {
    .Call('_divergenceModelR_skewnessSwapRateCpp', PACKAGE = 'divergenceModelR', p, coeffs, stateMat)
}

#' @export
quarticitySwapRateCpp <- function(p, coeffs, stateMat) {
    .Call('_divergenceModelR_quarticitySwapRateCpp', PACKAGE = 'divergenceModelR', p, coeffs, stateMat)
}

#'@export
glPricer_cpp <- function(strikeMat, mkt, glWts, glNodes, cfVals, Nfactors, alpha = 0, sigmaRef = 1.0) {
    .Call('_divergenceModelR_glPricer_cpp', PACKAGE = 'divergenceModelR', strikeMat, mkt, glWts, glNodes, cfVals, Nfactors, alpha, sigmaRef)
}

#' @export
meanVecFun <- function(meanListS, currVol) {
    .Call('_divergenceModelR_meanVecFun', PACKAGE = 'divergenceModelR', meanListS, currVol)
}

#' @useDynLib divergenceModelR
#' @export
testAffineFilter <- function(testDataMat, testInitState, testInitProcCov, testModelParams) {
    .Call('_divergenceModelR_testAffineFilter', PACKAGE = 'divergenceModelR', testDataMat, testInitState, testInitProcCov, testModelParams)
}

#' @export
testSqrtAffineFilter <- function(testDataMat, testInitState, testInitProcCov, testModelParams) {
    .Call('_divergenceModelR_testSqrtAffineFilter', PACKAGE = 'divergenceModelR', testDataMat, testInitState, testInitProcCov, testModelParams)
}

